# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd54fa9e2b18f1f12186aa39517c7303e424968fcc4049bcc8398029b68d4d25b91b6809eb2233508d7858f518c93634edfd22f07ecd80dca3959a6928cc35d

test:
  secret_key_base: fd2b586c4ab6b3d739b7da50d1acb04d19fa90e2914261e11f9ea4053dd990f1a13b48a80cf99ecab485c509532b66c879cc0b0e3ac09338f6ebcc20940b88b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3de2e3ab82c6a28fc08561a501c447ff629e5997de606e8c587a0b47161f5515b9b86e9c2cffd51021f42b3e30fd13d0611a1aca49543f70d8d2311adc178bf5
